CREATE TABLE parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    category VARCHAR(30) NOT NULL,
    venue_name VARCHAR(120) NOT NULL,
    venue_address VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    capacity INT NOT NULL CHECK (capacity BETWEEN 2 AND 30),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_parties_public ON parties(status, starts_at);
CREATE INDEX idx_parties_location ON parties(latitude, longitude);

CREATE TABLE party_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (party_id, user_id)
);
CREATE INDEX idx_party_members_user ON party_members(user_id);
